# Generated by Django 3.1.3 on 2021-05-08 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import restaurant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField(blank=True, default=restaurant.models.get_current_time)),
                ('is_active', models.BooleanField(default=True)),
                ('order_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('category', models.CharField(choices=[('AP', 'закуски'), ('SO', 'супы'), ('SA', 'салаты'), ('MD', 'основные блюда'), ('SI', 'гарниры'), ('SN', 'закуски'), ('DE', 'десерты'), ('DN', 'напитки')], max_length=2, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveIntegerField(unique=True)),
                ('is_available', models.BooleanField(default=True, help_text='If the table is free-True, busy-False', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['is_available'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField(blank=True, default=restaurant.models.get_current_time)),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Product amount')),
                ('order_item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Position cost')),
                ('is_ready', models.BooleanField(blank=True, default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='restaurant.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='restaurant.product', verbose_name='Позиция меню')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table', verbose_name='Стол'),
        ),
    ]
